name: tests

on:
  pull_request:
    branches:
      - "14.0*"
  push:
    branches:
      - "14.0"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build docker image
        run: |
          git config --global init.defaultBranch main
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          pip install git-aggregator
          cd _docker
          mkdir -p  odoo/local-src odoo/external-src data songs
          cp -r ../ps_{account,account_payment_order_operating_unit,assets_equipment_link,calendar,contract,crm,date_range_week,equipment,expense,fleet,fleet_rdw,landing_page,hr,holidays,klippa,timesheet_invoicing,partner_multi_relation,planning,project} odoo/local-src
          cd odoo/external-src
          gitaggregate -c ../../../repos.yml
          cd ../..
          cp ../requirements.txt .
          docker compose build
      - name: Run tests
        run: |
          cd _docker
          docker compose run --name odoo_runtests odoo sh -c "runtests && coverage xml"
          docker cp odoo_runtests:/odoo/coverage.xml ..
      - uses: codecov/codecov-action@v3
        with:
          files: coverage.xml
